#!/sbin/openrc-run

description="Explicitly removes webcam device."

depend() {
        before firewall
        after logger
}

start() {
	eindent
		veinfo "Starting pci removal script"
	eoutdent
}

stop() {
        ebegin "Triggering remove for PCI webcam devices"
        eindent
                veinfo "Processing $device"
                echo 1 > /sys/devices/pci0000:00/0000:00:07.0/remove
        eoutdent

        eend $?
}
